name: poky-container build and test
on:
  push:
    branches:
      - master
      - ubuntu-24.04-lts
  pull_request:

  # Allow for manually running
  workflow_dispatch:

  # Run at 01:42 UTC every Saturday
  schedule:
    - cron: '42 1 * * 6'

jobs:
  build-test-deploy:
    runs-on: ${{ matrix.targetplatform == 'linux/amd64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        base_distro: [
                      ubuntu-22.04,
                      ubuntu-24.04
        ]
        targetplatform: [
          linux/amd64,
          linux/arm64
        ]
    env:
      BASE_DISTRO: ${{ matrix.base_distro }}
      TARGETPLATFORM: ${{ matrix.targetplatform }}
      REPO: crops/poky
      DEFAULT_DISTRO: ubuntu-18.04
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GHCR_USERNAME: ${{ github.actor }}
      GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v5

      # Build and test the images
      - name: Run build-and-test.sh
        run: ./build-and-test.sh && for docker_image in $(docker images -q); do docker inspect --format='{{.Os}}/{{.Architecture}} {{.RepoTags}}' ${docker_image}; done

      # Deploy the images
      - name: Deploy
        if: ${{ env.DOCKER_PASSWORD != '' && env.GHCR_PASSWORD != '' }}
        run: bash deploy.sh
